name=GyverPush
version=1.0.0
author=AlexGyver <alex@alexgyver.ru>
maintainer=AlexGyver <alex@alexgyver.ru>
sentence=
paragraph=
category=Display Communication Signal Input/Output Sensors Device Control Timing Data Storage Data Processing Other
url=https://github.com/GyverLibs/GyverPush
depends=GyverIO
architectures=*